create table instructor_mock (
	instructor_id INT,
	fName VARCHAR(50),
	lName VARCHAR(50),
	expertize VARCHAR(50),
	gym_id INT
);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (1, 'Yulma', 'Gulliford', 'Weight Lose', 12);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (2, 'Ninnetta', 'Leele', 'Weight Lose', 11);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (3, 'Tillie', 'Goforth', 'Nutritionist', 9);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (4, 'Marco', 'Mews', 'Tone up', 10);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (5, 'Sianna', 'Cockings', 'Weight Lose', 9);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (6, 'Flem', 'Sinden', 'Tone up', 3);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (7, 'Cristal', 'Dorant', 'Nutritionist', 9);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (8, 'Dame', 'Totterdill', 'Weight Lose', 8);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (9, 'Mischa', 'Thomesson', 'Nutritionist', 20);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (10, 'Geordie', 'Peacey', 'Weight Lose', 5);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (11, 'Evaleen', 'Richings', 'Tone up', 8);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (12, 'Giustino', 'Foley', 'Muscle gain', 17);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (13, 'Catlin', 'Have', 'Tone up', 14);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (14, 'Rhett', 'McCraw', 'Nutritionist', 9);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (15, 'Jennine', 'Batchelour', 'Tone up', 16);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (16, 'Odille', 'Helks', 'Muscle gain', 3);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (17, 'Daune', 'Muttock', 'Weight Lose', 13);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (18, 'See', 'Keenan', 'Nutritionist', 1);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (19, 'Rasla', 'Edyson', 'Tone up', 9);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (20, 'Antoinette', 'Josipovitz', 'Tone up', 18);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (21, 'Aloise', 'Blade', 'Tone up', 13);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (22, 'Alayne', 'Shurville', 'Muscle gain', 15);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (23, 'Ericha', 'Casine', 'Weight Lose', 3);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (24, 'Wes', 'Rabl', 'Tone up', 10);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (25, 'Marylee', 'Ashpital', 'Tone up', 9);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (26, 'Sheree', 'Bleasby', 'Nutritionist', 6);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (27, 'Gregory', 'Allom', 'Tone up', 3);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (28, 'Aleece', 'Ruckman', 'Muscle gain', 9);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (29, 'Maisey', 'Strover', 'Nutritionist', 7);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (30, 'Isac', 'Pautard', 'Muscle gain', 4);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (31, 'Hobey', 'Liversedge', 'Weight Lose', 10);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (32, 'Shepperd', 'Harmeston', 'Muscle gain', 11);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (33, 'Sancho', 'Giacovazzo', 'Nutritionist', 7);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (34, 'Brandy', 'Robbe', 'Tone up', 13);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (35, 'Kip', 'Joberne', 'Muscle gain', 7);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (36, 'Leigha', 'Lahrs', 'Tone up', 20);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (37, 'Karola', 'Semiraz', 'Muscle gain', 20);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (38, 'Rochester', 'Beed', 'Muscle gain', 13);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (39, 'Nat', 'Boughey', 'Nutritionist', 16);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (40, 'Ebonee', 'Ipsgrave', 'Weight Lose', 7);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (41, 'Hillery', 'Cranke', 'Tone up', 17);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (42, 'Debor', 'Whitney', 'Nutritionist', 8);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (43, 'Francklyn', 'Capinetti', 'Nutritionist', 14);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (44, 'Corly', 'Worledge', 'Weight Lose', 17);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (45, 'Ashlie', 'Fritschmann', 'Weight Lose', 15);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (46, 'Sarene', 'Pear', 'Weight Lose', 2);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (47, 'Devondra', 'Follos', 'Nutritionist', 5);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (48, 'Carlyle', 'Guinan', 'Nutritionist', 9);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (49, 'Micky', 'Radbourne', 'Weight Lose', 6);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (50, 'Val', 'Presdee', 'Nutritionist', 15);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (51, 'Winnie', 'Meriot', 'Muscle gain', 20);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (52, 'Marshal', 'Lownsbrough', 'Weight Lose', 11);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (53, 'Shay', 'Gietz', 'Muscle gain', 9);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (54, 'Sibyl', 'Di Bartolomeo', 'Muscle gain', 15);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (55, 'Hewet', 'Challiner', 'Weight Lose', 16);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (56, 'Hulda', 'Chastney', 'Weight Lose', 19);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (57, 'Haily', 'Tarling', 'Nutritionist', 5);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (58, 'Ramsay', 'Burchill', 'Weight Lose', 17);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (59, 'Terza', 'Quade', 'Muscle gain', 14);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (60, 'Anna', 'Dundridge', 'Nutritionist', 9);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (61, 'Kennedy', 'Beevers', 'Weight Lose', 8);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (62, 'Fraser', 'Stirley', 'Nutritionist', 12);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (63, 'Em', 'Corkan', 'Muscle gain', 12);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (64, 'Cello', 'Mebes', 'Muscle gain', 6);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (65, 'Andres', 'Cressar', 'Tone up', 17);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (66, 'Mabelle', 'Goodbur', 'Muscle gain', 14);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (67, 'Thorstein', 'Pridden', 'Muscle gain', 2);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (68, 'Abbey', 'Tuplin', 'Nutritionist', 8);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (69, 'Byrann', 'Filkov', 'Tone up', 17);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (70, 'Edgardo', 'Walkington', 'Tone up', 7);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (71, 'Shell', 'Stearn', 'Weight Lose', 5);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (72, 'Shirleen', 'Corpes', 'Tone up', 17);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (73, 'Jenine', 'Mosedale', 'Nutritionist', 18);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (74, 'Durand', 'Lindsey', 'Muscle gain', 15);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (75, 'Alysia', 'Childerhouse', 'Tone up', 18);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (76, 'Cathlene', 'Barraclough', 'Weight Lose', 15);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (77, 'Kaine', 'Rablen', 'Weight Lose', 12);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (78, 'Anastasia', 'Garfath', 'Tone up', 19);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (79, 'Harris', 'Gherarducci', 'Muscle gain', 4);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (80, 'Johna', 'Dyball', 'Weight Lose', 15);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (81, 'Nicolina', 'Couldwell', 'Muscle gain', 5);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (82, 'Serena', 'Siddens', 'Muscle gain', 4);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (83, 'Shayne', 'Dobbison', 'Nutritionist', 17);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (84, 'Andy', 'Durbridge', 'Weight Lose', 18);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (85, 'Emlyn', 'Dani', 'Weight Lose', 19);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (86, 'Lulita', 'Wingrove', 'Weight Lose', 11);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (87, 'Annabelle', 'Petrina', 'Nutritionist', 15);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (88, 'Kerrin', 'Aslie', 'Muscle gain', 19);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (89, 'Orsa', 'Mocher', 'Nutritionist', 3);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (90, 'Donni', 'Ormrod', 'Weight Lose', 17);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (91, 'Charla', 'Oluwatoyin', 'Weight Lose', 13);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (92, 'Judith', 'Arlt', 'Nutritionist', 20);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (93, 'Kare', 'Bloyes', 'Nutritionist', 19);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (94, 'Edna', 'Schimek', 'Weight Lose', 11);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (95, 'Candice', 'De Bernardi', 'Muscle gain', 14);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (96, 'Skipp', 'Besse', 'Nutritionist', 19);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (97, 'Delilah', 'Hunter', 'Muscle gain', 2);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (98, 'Abe', 'Dibnah', 'Tone up', 7);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (99, 'Helenka', 'Pointon', 'Tone up', 14);
insert into instructor_mock (instructor_id, fName, lName, expertize, gym_id) values (100, 'Gerri', 'Arrowsmith', 'Nutritionist', 10);
