create table class_mock (
	id INT,
	class_name VARCHAR(50),
	class_type VARCHAR(50),
	start_time VARCHAR(50),
	end_time VARCHAR(50),
	class_size INT,
	enroll DECIMAL(3,2),
	instructor INT
);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (1, 'Curls n’ Crunches', 'Cardio', '5:03 PM', '4:19 PM', 10, 0.82, 63);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (2, 'Power Hour', 'Cardio', '11:59 AM', '1:56 PM', 30, 0.54, 31);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (3, 'Power Hour', 'Abs', '3:40 PM', '9:28 AM', 22, 0.36, 44);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (4, 'Curls n’ Crunches', 'Cardio', '5:13 PM', '2:35 PM', 10, 0.13, 78);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (5, 'Walk this Weigh', 'Abs', '11:14 AM', '3:59 PM', 11, 0.48, 99);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (6, 'Walk this Weigh', 'Abs', '1:52 PM', '9:43 AM', 28, 0.5, 36);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (7, 'Walk this Weigh', 'Abs', '12:19 PM', '3:42 PM', 13, 0.7, 38);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (8, 'Move it, Shake it, Lift it', 'Abs', '2:10 PM', '3:56 PM', 30, 0.28, 81);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (9, 'Fab & Fit & Fun', 'Abs', '2:27 PM', '6:45 PM', 6, 0.09, 13);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (10, 'Wishful Shrinking', 'Strength', '1:20 PM', '5:46 PM', 23, 0.98, 43);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (11, 'Power Hour', 'Abs', '12:03 PM', '5:31 PM', 26, 0.26, 38);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (12, 'Walk this Weigh', 'Abs', '11:43 AM', '6:50 PM', 17, 0.32, 6);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (13, 'Curls n’ Crunches', 'Abs', '12:32 PM', '12:04 PM', 14, 0.42, 38);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (14, 'Move it, Shake it, Lift it', 'Cardio', '1:20 PM', '2:34 PM', 10, 0.95, 44);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (15, 'Walk this Weigh', 'Cardio', '4:39 PM', '1:03 PM', 19, 0.27, 93);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (16, 'Power Hour', 'Cardio', '5:50 PM', '7:23 PM', 12, 0.11, 54);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (17, 'Walk this Weigh', 'Cardio', '12:56 PM', '3:49 PM', 21, 0.94, 79);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (18, 'Fab & Fit & Fun', 'Yoga', '8:30 AM', '5:23 PM', 30, 0.23, 71);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (19, 'Fab & Fit & Fun', 'Cardio', '3:56 PM', '2:33 PM', 8, 0.46, 53);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (20, 'Walk this Weigh', 'Cardio', '4:40 PM', '6:20 PM', 8, 0.94, 5);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (21, 'Sweat', 'Strength', '1:45 PM', '10:55 AM', 22, 0.73, 45);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (22, 'Curls n’ Crunches', 'Abs', '1:23 PM', '9:54 AM', 18, 0.82, 40);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (23, 'Sweat', 'Yoga', '3:40 PM', '5:50 PM', 20, 0.9, 70);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (24, 'Curls n’ Crunches', 'Strength', '12:42 PM', '9:50 AM', 15, 0.68, 66);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (25, 'Abs Fab / Fab Abs', 'Cardio', '12:27 PM', '6:22 PM', 23, 0.76, 9);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (26, 'Sweat', 'Strength', '3:25 PM', '12:36 PM', 10, 0.04, 63);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (27, 'Sweat', 'Cardio', '12:54 PM', '3:45 PM', 23, 0.77, 3);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (28, 'Fab & Fit & Fun', 'Yoga', '12:54 PM', '6:33 PM', 28, 0.93, 57);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (29, 'Curls n’ Crunches', 'Cardio', '9:01 AM', '12:24 PM', 13, 0.87, 14);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (30, 'Power Hour', 'Cardio', '3:50 PM', '11:11 AM', 15, 0.03, 49);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (31, 'Abs Fab / Fab Abs', 'Yoga', '4:36 PM', '5:02 PM', 22, 0.2, 49);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (32, 'Curls n’ Crunches', 'Cardio', '1:51 PM', '6:15 PM', 24, 0.62, 91);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (33, 'Fab & Fit & Fun', 'Cardio', '9:14 AM', '12:57 PM', 24, 0.15, 56);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (34, 'Power Hour', 'Yoga', '10:14 AM', '10:11 AM', 15, 0.93, 23);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (35, 'Fab & Fit & Fun', 'Cardio', '1:34 PM', '5:57 PM', 7, 0.41, 50);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (36, 'Power Hour', 'Cardio', '11:16 AM', '1:35 PM', 23, 0.53, 66);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (37, 'Wishful Shrinking', 'Strength', '2:18 PM', '2:07 PM', 25, 0.93, 77);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (38, 'Curls n’ Crunches', 'Cardio', '8:53 AM', '9:59 AM', 28, 0.26, 77);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (39, 'Curls n’ Crunches', 'Strength', '10:39 AM', '7:09 PM', 11, 0.8, 22);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (40, 'Sweat', 'Strength', '11:00 AM', '9:06 AM', 12, 0.21, 34);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (41, 'Power Hour', 'Cardio', '1:15 PM', '12:55 PM', 11, 0.5, 35);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (42, 'Walk this Weigh', 'Cardio', '2:48 PM', '5:42 PM', 9, 0.29, 83);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (43, 'Curls n’ Crunches', 'Cardio', '1:50 PM', '6:31 PM', 15, 0.17, 13);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (44, 'Sweat', 'Cardio', '8:55 AM', '4:31 PM', 24, 0.39, 9);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (45, 'Move it, Shake it, Lift it', 'Yoga', '3:57 PM', '11:52 AM', 29, 0.79, 18);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (46, 'Abs Fab / Fab Abs', 'Cardio', '10:43 AM', '7:08 PM', 17, 0.02, 31);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (47, 'Walk this Weigh', 'Cardio', '5:54 PM', '10:59 AM', 26, 0.8, 57);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (48, 'Fab & Fit & Fun', 'Abs', '12:33 PM', '4:55 PM', 23, 0.25, 46);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (49, 'Sweat', 'Cardio', '11:02 AM', '6:59 PM', 20, 0.76, 80);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (50, 'Power Hour', 'Abs', '3:10 PM', '4:51 PM', 13, 0.88, 17);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (51, 'Power Hour', 'Cardio', '8:19 AM', '2:22 PM', 13, 0.26, 8);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (52, 'Curls n’ Crunches', 'Strength', '8:11 AM', '6:58 PM', 19, 0.75, 74);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (53, 'Power Hour', 'Strength', '10:23 AM', '1:59 PM', 27, 0.95, 3);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (54, 'Walk this Weigh', 'Strength', '1:50 PM', '6:13 PM', 28, 0.99, 15);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (55, 'Sweat', 'Abs', '8:28 AM', '12:48 PM', 9, 0.82, 25);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (56, 'Power Hour', 'Cardio', '11:38 AM', '6:37 PM', 18, 0.41, 44);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (57, 'Curls n’ Crunches', 'Cardio', '5:37 PM', '1:42 PM', 12, 0.7, 70);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (58, 'Walk this Weigh', 'Cardio', '11:46 AM', '10:57 AM', 16, 0.14, 49);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (59, 'Walk this Weigh', 'Cardio', '4:14 PM', '10:16 AM', 27, 0.15, 46);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (60, 'Move it, Shake it, Lift it', 'Abs', '3:16 PM', '2:40 PM', 30, 0.42, 33);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (61, 'Move it, Shake it, Lift it', 'Strength', '1:46 PM', '11:02 AM', 28, 0.32, 55);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (62, 'Sweat', 'Yoga', '8:20 AM', '11:26 AM', 12, 0.93, 60);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (63, 'Sweat', 'Yoga', '8:29 AM', '4:17 PM', 27, 0.97, 79);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (64, 'Power Hour', 'Cardio', '11:54 AM', '5:13 PM', 11, 0.5, 75);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (65, 'Sweat', 'Cardio', '8:55 AM', '1:20 PM', 12, 0.95, 70);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (66, 'Move it, Shake it, Lift it', 'Cardio', '2:11 PM', '4:44 PM', 13, 0.72, 65);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (67, 'Fab & Fit & Fun', 'Cardio', '11:18 AM', '12:18 PM', 29, 0.63, 7);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (68, 'Curls n’ Crunches', 'Cardio', '11:11 AM', '5:59 PM', 22, 0.72, 13);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (69, 'Walk this Weigh', 'Cardio', '11:26 AM', '1:37 PM', 30, 0.16, 42);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (70, 'Move it, Shake it, Lift it', 'Abs', '9:20 AM', '1:13 PM', 11, 0.4, 20);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (71, 'Power Hour', 'Cardio', '1:55 PM', '12:46 PM', 21, 0.66, 42);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (72, 'Abs Fab / Fab Abs', 'Strength', '3:27 PM', '1:07 PM', 21, 0.16, 65);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (73, 'Fab & Fit & Fun', 'Yoga', '10:06 AM', '2:37 PM', 13, 0.03, 32);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (74, 'Move it, Shake it, Lift it', 'Strength', '2:56 PM', '1:08 PM', 20, 0.13, 61);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (75, 'Fab & Fit & Fun', 'Cardio', '4:05 PM', '3:15 PM', 17, 0.53, 23);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (76, 'Curls n’ Crunches', 'Strength', '1:22 PM', '6:59 PM', 27, 0.34, 12);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (77, 'Wishful Shrinking', 'Strength', '12:49 PM', '3:49 PM', 19, 0.55, 15);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (78, 'Walk this Weigh', 'Strength', '2:16 PM', '6:23 PM', 5, 0.46, 6);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (79, 'Sweat', 'Cardio', '1:41 PM', '12:18 PM', 24, 0.05, 84);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (80, 'Sweat', 'Cardio', '1:52 PM', '11:23 AM', 26, 0.19, 97);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (81, 'Curls n’ Crunches', 'Abs', '8:07 AM', '6:13 PM', 23, 0.31, 31);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (82, 'Sweat', 'Strength', '5:28 PM', '5:44 PM', 21, 0.84, 35);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (83, 'Fab & Fit & Fun', 'Cardio', '11:16 AM', '1:52 PM', 29, 0.02, 32);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (84, 'Move it, Shake it, Lift it', 'Abs', '8:01 AM', '6:26 PM', 23, 0.85, 18);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (85, 'Walk this Weigh', 'Cardio', '10:18 AM', '10:25 AM', 12, 0.65, 87);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (86, 'Sweat', 'Abs', '5:25 PM', '10:52 AM', 20, 0.74, 82);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (87, 'Curls n’ Crunches', 'Cardio', '11:47 AM', '4:56 PM', 27, 0.13, 98);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (88, 'Wishful Shrinking', 'Strength', '4:37 PM', '12:47 PM', 27, 0.87, 33);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (89, 'Sweat', 'Cardio', '2:15 PM', '7:10 PM', 20, 0.74, 5);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (90, 'Power Hour', 'Cardio', '9:40 AM', '2:10 PM', 11, 0.72, 41);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (91, 'Fab & Fit & Fun', 'Cardio', '9:51 AM', '9:39 AM', 11, 0.08, 88);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (92, 'Walk this Weigh', 'Cardio', '9:02 AM', '11:42 AM', 16, 0.25, 24);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (93, 'Wishful Shrinking', 'Yoga', '2:39 PM', '6:04 PM', 20, 0.75, 86);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (94, 'Abs Fab / Fab Abs', 'Cardio', '5:49 PM', '10:16 AM', 21, 0.13, 22);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (95, 'Power Hour', 'Cardio', '10:08 AM', '4:03 PM', 12, 1.0, 4);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (96, 'Walk this Weigh', 'Abs', '11:27 AM', '10:32 AM', 19, 0.68, 50);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (97, 'Wishful Shrinking', 'Cardio', '2:12 PM', '11:02 AM', 15, 0.31, 36);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (98, 'Abs Fab / Fab Abs', 'Abs', '10:02 AM', '11:12 AM', 11, 0.72, 37);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (99, 'Move it, Shake it, Lift it', 'Abs', '8:43 AM', '4:52 PM', 22, 0.49, 95);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (100, 'Wishful Shrinking', 'Cardio', '11:53 AM', '7:21 PM', 15, 0.52, 33);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (101, 'Curls n’ Crunches', 'Cardio', '12:44 PM', '12:59 PM', 15, 0.94, 85);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (102, 'Walk this Weigh', 'Cardio', '3:00 PM', '2:33 PM', 27, 0.77, 32);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (103, 'Fab & Fit & Fun', 'Cardio', '8:11 AM', '3:55 PM', 27, 0.66, 27);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (104, 'Wishful Shrinking', 'Abs', '9:40 AM', '12:00 PM', 10, 0.94, 90);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (105, 'Abs Fab / Fab Abs', 'Cardio', '1:17 PM', '12:55 PM', 12, 0.07, 69);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (106, 'Abs Fab / Fab Abs', 'Cardio', '9:13 AM', '10:34 AM', 17, 0.81, 53);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (107, 'Wishful Shrinking', 'Abs', '3:53 PM', '3:20 PM', 29, 0.23, 64);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (108, 'Sweat', 'Strength', '9:53 AM', '2:53 PM', 24, 0.16, 48);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (109, 'Sweat', 'Cardio', '10:12 AM', '4:22 PM', 13, 0.65, 93);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (110, 'Fab & Fit & Fun', 'Strength', '11:41 AM', '6:51 PM', 27, 0.15, 80);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (111, 'Walk this Weigh', 'Yoga', '2:25 PM', '11:40 AM', 5, 0.53, 62);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (112, 'Move it, Shake it, Lift it', 'Cardio', '1:47 PM', '5:41 PM', 29, 0.85, 29);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (113, 'Curls n’ Crunches', 'Yoga', '4:52 PM', '1:35 PM', 29, 0.15, 62);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (114, 'Sweat', 'Abs', '11:12 AM', '12:46 PM', 27, 0.72, 50);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (115, 'Curls n’ Crunches', 'Cardio', '10:39 AM', '3:46 PM', 23, 0.19, 86);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (116, 'Power Hour', 'Abs', '5:33 PM', '12:09 PM', 15, 0.0, 86);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (117, 'Walk this Weigh', 'Cardio', '11:43 AM', '4:46 PM', 18, 0.02, 24);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (118, 'Power Hour', 'Abs', '8:52 AM', '6:27 PM', 23, 0.46, 20);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (119, 'Move it, Shake it, Lift it', 'Abs', '12:21 PM', '6:10 PM', 12, 0.18, 24);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (120, 'Abs Fab / Fab Abs', 'Yoga', '10:46 AM', '3:49 PM', 17, 0.46, 54);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (121, 'Power Hour', 'Strength', '2:21 PM', '3:00 PM', 15, 0.81, 55);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (122, 'Walk this Weigh', 'Cardio', '9:39 AM', '2:31 PM', 24, 0.3, 72);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (123, 'Sweat', 'Strength', '9:00 AM', '7:24 PM', 8, 0.36, 73);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (124, 'Power Hour', 'Cardio', '11:44 AM', '1:24 PM', 13, 0.44, 96);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (125, 'Power Hour', 'Abs', '12:15 PM', '11:18 AM', 18, 0.87, 100);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (126, 'Sweat', 'Cardio', '11:16 AM', '9:48 AM', 20, 0.96, 18);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (127, 'Abs Fab / Fab Abs', 'Yoga', '8:13 AM', '3:53 PM', 28, 0.44, 63);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (128, 'Wishful Shrinking', 'Abs', '8:22 AM', '11:27 AM', 6, 0.65, 32);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (129, 'Abs Fab / Fab Abs', 'Cardio', '1:01 PM', '6:07 PM', 5, 0.08, 58);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (130, 'Move it, Shake it, Lift it', 'Yoga', '12:05 PM', '10:11 AM', 20, 0.43, 4);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (131, 'Abs Fab / Fab Abs', 'Cardio', '11:07 AM', '6:32 PM', 19, 0.62, 16);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (132, 'Walk this Weigh', 'Yoga', '2:32 PM', '2:21 PM', 24, 0.87, 37);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (133, 'Sweat', 'Strength', '12:47 PM', '9:48 AM', 20, 0.4, 68);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (134, 'Walk this Weigh', 'Cardio', '3:15 PM', '2:53 PM', 30, 0.09, 78);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (135, 'Fab & Fit & Fun', 'Strength', '8:48 AM', '12:32 PM', 10, 0.72, 40);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (136, 'Wishful Shrinking', 'Strength', '4:31 PM', '4:12 PM', 25, 0.7, 52);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (137, 'Abs Fab / Fab Abs', 'Strength', '11:15 AM', '4:56 PM', 18, 0.16, 89);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (138, 'Wishful Shrinking', 'Cardio', '10:01 AM', '5:28 PM', 8, 0.94, 45);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (139, 'Walk this Weigh', 'Abs', '9:00 AM', '4:36 PM', 19, 0.08, 5);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (140, 'Fab & Fit & Fun', 'Yoga', '2:40 PM', '1:11 PM', 30, 0.74, 30);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (141, 'Curls n’ Crunches', 'Cardio', '2:31 PM', '4:28 PM', 26, 0.29, 44);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (142, 'Walk this Weigh', 'Yoga', '12:29 PM', '2:59 PM', 28, 0.23, 86);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (143, 'Curls n’ Crunches', 'Abs', '12:26 PM', '6:25 PM', 22, 0.15, 81);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (144, 'Abs Fab / Fab Abs', 'Cardio', '12:52 PM', '12:30 PM', 11, 0.02, 28);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (145, 'Power Hour', 'Cardio', '12:14 PM', '3:21 PM', 12, 0.97, 81);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (146, 'Move it, Shake it, Lift it', 'Abs', '11:54 AM', '12:58 PM', 28, 0.54, 46);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (147, 'Wishful Shrinking', 'Cardio', '10:42 AM', '7:29 PM', 21, 0.67, 77);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (148, 'Sweat', 'Cardio', '5:27 PM', '10:16 AM', 5, 0.56, 56);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (149, 'Power Hour', 'Yoga', '10:40 AM', '11:08 AM', 6, 0.38, 34);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (150, 'Abs Fab / Fab Abs', 'Cardio', '10:07 AM', '9:51 AM', 24, 0.35, 16);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (151, 'Power Hour', 'Yoga', '4:34 PM', '9:35 AM', 23, 0.31, 19);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (152, 'Curls n’ Crunches', 'Cardio', '8:38 AM', '9:06 AM', 12, 0.5, 10);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (153, 'Sweat', 'Strength', '1:21 PM', '4:53 PM', 19, 0.54, 35);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (154, 'Move it, Shake it, Lift it', 'Strength', '9:22 AM', '12:55 PM', 15, 0.99, 53);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (155, 'Abs Fab / Fab Abs', 'Abs', '2:01 PM', '10:15 AM', 10, 0.89, 60);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (156, 'Sweat', 'Cardio', '5:19 PM', '11:59 AM', 29, 0.33, 93);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (157, 'Sweat', 'Cardio', '11:10 AM', '3:30 PM', 21, 0.59, 7);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (158, 'Move it, Shake it, Lift it', 'Cardio', '9:13 AM', '4:56 PM', 8, 0.48, 62);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (159, 'Curls n’ Crunches', 'Strength', '11:58 AM', '5:03 PM', 13, 0.01, 6);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (160, 'Abs Fab / Fab Abs', 'Cardio', '12:31 PM', '9:39 AM', 21, 0.61, 75);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (161, 'Wishful Shrinking', 'Cardio', '2:33 PM', '6:18 PM', 21, 0.79, 54);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (162, 'Move it, Shake it, Lift it', 'Cardio', '4:40 PM', '6:31 PM', 15, 0.3, 8);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (163, 'Fab & Fit & Fun', 'Cardio', '3:17 PM', '1:57 PM', 11, 0.71, 71);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (164, 'Power Hour', 'Yoga', '11:05 AM', '5:42 PM', 17, 0.4, 77);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (165, 'Wishful Shrinking', 'Strength', '8:13 AM', '5:14 PM', 5, 0.71, 33);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (166, 'Power Hour', 'Cardio', '1:12 PM', '11:48 AM', 10, 0.31, 71);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (167, 'Power Hour', 'Abs', '11:44 AM', '4:46 PM', 9, 0.27, 20);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (168, 'Walk this Weigh', 'Yoga', '10:50 AM', '6:52 PM', 27, 0.39, 17);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (169, 'Abs Fab / Fab Abs', 'Cardio', '11:31 AM', '2:32 PM', 5, 0.65, 75);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (170, 'Abs Fab / Fab Abs', 'Strength', '4:46 PM', '11:37 AM', 7, 0.08, 91);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (171, 'Curls n’ Crunches', 'Cardio', '5:52 PM', '9:26 AM', 30, 0.29, 66);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (172, 'Sweat', 'Yoga', '8:13 AM', '5:06 PM', 29, 0.3, 14);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (173, 'Abs Fab / Fab Abs', 'Cardio', '8:04 AM', '9:09 AM', 17, 0.25, 46);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (174, 'Curls n’ Crunches', 'Cardio', '9:05 AM', '4:09 PM', 12, 0.7, 34);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (175, 'Power Hour', 'Cardio', '5:28 PM', '5:30 PM', 22, 0.34, 88);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (176, 'Move it, Shake it, Lift it', 'Abs', '11:09 AM', '9:17 AM', 15, 0.57, 36);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (177, 'Power Hour', 'Cardio', '10:05 AM', '12:51 PM', 15, 0.71, 1);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (178, 'Sweat', 'Yoga', '1:47 PM', '3:22 PM', 23, 0.89, 8);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (179, 'Power Hour', 'Cardio', '5:45 PM', '4:19 PM', 22, 0.42, 63);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (180, 'Power Hour', 'Cardio', '12:55 PM', '9:46 AM', 8, 0.23, 7);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (181, 'Fab & Fit & Fun', 'Yoga', '2:10 PM', '2:02 PM', 17, 0.44, 100);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (182, 'Sweat', 'Abs', '2:15 PM', '10:30 AM', 8, 0.75, 18);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (183, 'Move it, Shake it, Lift it', 'Cardio', '2:02 PM', '6:01 PM', 8, 0.37, 51);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (184, 'Abs Fab / Fab Abs', 'Abs', '10:48 AM', '5:34 PM', 29, 0.11, 15);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (185, 'Abs Fab / Fab Abs', 'Cardio', '10:56 AM', '5:00 PM', 21, 0.63, 59);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (186, 'Walk this Weigh', 'Abs', '3:10 PM', '2:37 PM', 21, 0.88, 43);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (187, 'Sweat', 'Cardio', '10:40 AM', '3:45 PM', 15, 0.06, 82);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (188, 'Move it, Shake it, Lift it', 'Cardio', '9:47 AM', '3:20 PM', 13, 0.3, 79);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (189, 'Move it, Shake it, Lift it', 'Abs', '8:12 AM', '3:44 PM', 13, 0.92, 15);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (190, 'Sweat', 'Cardio', '10:37 AM', '1:41 PM', 15, 0.59, 93);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (191, 'Abs Fab / Fab Abs', 'Cardio', '1:24 PM', '4:28 PM', 24, 0.65, 96);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (192, 'Abs Fab / Fab Abs', 'Cardio', '5:07 PM', '10:50 AM', 30, 0.36, 34);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (193, 'Abs Fab / Fab Abs', 'Cardio', '10:44 AM', '7:27 PM', 6, 0.0, 57);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (194, 'Move it, Shake it, Lift it', 'Cardio', '5:56 PM', '9:04 AM', 18, 0.41, 71);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (195, 'Fab & Fit & Fun', 'Abs', '5:42 PM', '9:17 AM', 6, 0.9, 46);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (196, 'Wishful Shrinking', 'Strength', '8:58 AM', '6:55 PM', 23, 0.96, 43);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (197, 'Wishful Shrinking', 'Cardio', '11:12 AM', '1:53 PM', 5, 0.13, 58);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (198, 'Power Hour', 'Cardio', '5:58 PM', '4:04 PM', 29, 0.81, 67);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (199, 'Move it, Shake it, Lift it', 'Cardio', '11:55 AM', '3:34 PM', 26, 0.68, 17);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (200, 'Move it, Shake it, Lift it', 'Abs', '4:00 PM', '5:09 PM', 8, 0.79, 10);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (201, 'Wishful Shrinking', 'Cardio', '4:57 PM', '4:06 PM', 17, 0.98, 43);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (202, 'Move it, Shake it, Lift it', 'Cardio', '12:41 PM', '10:28 AM', 30, 0.85, 42);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (203, 'Curls n’ Crunches', 'Cardio', '11:37 AM', '11:51 AM', 27, 0.47, 71);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (204, 'Abs Fab / Fab Abs', 'Cardio', '1:24 PM', '9:19 AM', 14, 0.61, 44);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (205, 'Abs Fab / Fab Abs', 'Abs', '12:52 PM', '6:35 PM', 20, 0.72, 16);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (206, 'Abs Fab / Fab Abs', 'Yoga', '2:47 PM', '6:24 PM', 7, 0.73, 66);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (207, 'Abs Fab / Fab Abs', 'Cardio', '11:53 AM', '2:58 PM', 23, 0.76, 81);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (208, 'Walk this Weigh', 'Cardio', '12:49 PM', '10:16 AM', 20, 0.95, 22);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (209, 'Wishful Shrinking', 'Abs', '10:16 AM', '9:42 AM', 6, 0.41, 62);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (210, 'Walk this Weigh', 'Abs', '1:23 PM', '3:24 PM', 9, 0.44, 30);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (211, 'Curls n’ Crunches', 'Cardio', '1:16 PM', '5:58 PM', 10, 0.46, 51);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (212, 'Wishful Shrinking', 'Abs', '10:47 AM', '5:44 PM', 16, 0.99, 39);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (213, 'Walk this Weigh', 'Cardio', '2:47 PM', '4:58 PM', 20, 0.39, 93);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (214, 'Walk this Weigh', 'Abs', '8:33 AM', '12:51 PM', 23, 0.1, 61);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (215, 'Wishful Shrinking', 'Cardio', '3:33 PM', '2:03 PM', 26, 0.85, 22);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (216, 'Fab & Fit & Fun', 'Cardio', '12:42 PM', '6:48 PM', 13, 0.36, 95);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (217, 'Abs Fab / Fab Abs', 'Strength', '1:09 PM', '12:25 PM', 13, 0.13, 98);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (218, 'Fab & Fit & Fun', 'Abs', '8:21 AM', '3:05 PM', 17, 0.87, 34);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (219, 'Move it, Shake it, Lift it', 'Abs', '11:36 AM', '5:46 PM', 16, 0.37, 76);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (220, 'Curls n’ Crunches', 'Cardio', '5:45 PM', '10:05 AM', 9, 0.54, 73);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (221, 'Wishful Shrinking', 'Cardio', '12:54 PM', '3:22 PM', 24, 0.56, 84);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (222, 'Sweat', 'Cardio', '4:24 PM', '7:02 PM', 23, 0.96, 9);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (223, 'Sweat', 'Cardio', '11:05 AM', '3:56 PM', 8, 0.07, 26);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (224, 'Walk this Weigh', 'Abs', '12:47 PM', '2:44 PM', 22, 0.49, 70);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (225, 'Move it, Shake it, Lift it', 'Cardio', '2:56 PM', '2:39 PM', 16, 0.82, 92);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (226, 'Move it, Shake it, Lift it', 'Strength', '12:39 PM', '3:43 PM', 24, 0.84, 57);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (227, 'Abs Fab / Fab Abs', 'Cardio', '4:23 PM', '12:18 PM', 22, 0.56, 49);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (228, 'Wishful Shrinking', 'Cardio', '8:04 AM', '7:08 PM', 20, 0.18, 23);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (229, 'Move it, Shake it, Lift it', 'Cardio', '1:06 PM', '10:38 AM', 18, 0.78, 88);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (230, 'Walk this Weigh', 'Cardio', '9:29 AM', '3:57 PM', 29, 0.06, 13);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (231, 'Wishful Shrinking', 'Cardio', '2:21 PM', '6:35 PM', 9, 0.84, 19);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (232, 'Abs Fab / Fab Abs', 'Cardio', '9:48 AM', '4:45 PM', 12, 0.13, 93);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (233, 'Sweat', 'Cardio', '8:30 AM', '1:14 PM', 21, 0.05, 73);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (234, 'Move it, Shake it, Lift it', 'Abs', '10:48 AM', '9:49 AM', 28, 0.33, 61);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (235, 'Fab & Fit & Fun', 'Cardio', '12:27 PM', '7:27 PM', 20, 0.84, 90);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (236, 'Walk this Weigh', 'Yoga', '1:35 PM', '2:22 PM', 15, 0.36, 34);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (237, 'Curls n’ Crunches', 'Cardio', '10:23 AM', '3:31 PM', 23, 0.5, 48);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (238, 'Power Hour', 'Cardio', '9:20 AM', '7:09 PM', 6, 0.76, 89);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (239, 'Fab & Fit & Fun', 'Yoga', '4:15 PM', '7:28 PM', 17, 0.75, 18);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (240, 'Abs Fab / Fab Abs', 'Cardio', '10:21 AM', '10:34 AM', 30, 0.99, 9);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (241, 'Fab & Fit & Fun', 'Abs', '11:16 AM', '10:28 AM', 25, 0.39, 26);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (242, 'Wishful Shrinking', 'Cardio', '1:57 PM', '3:38 PM', 22, 0.11, 59);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (243, 'Abs Fab / Fab Abs', 'Cardio', '4:10 PM', '7:06 PM', 25, 0.12, 39);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (244, 'Power Hour', 'Strength', '10:42 AM', '5:56 PM', 23, 0.38, 13);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (245, 'Power Hour', 'Cardio', '11:47 AM', '1:55 PM', 19, 0.29, 41);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (246, 'Move it, Shake it, Lift it', 'Abs', '3:07 PM', '10:54 AM', 18, 0.47, 35);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (247, 'Sweat', 'Cardio', '9:55 AM', '3:26 PM', 20, 0.73, 57);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (248, 'Abs Fab / Fab Abs', 'Yoga', '5:14 PM', '1:17 PM', 5, 0.46, 19);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (249, 'Power Hour', 'Cardio', '5:52 PM', '2:46 PM', 25, 0.92, 64);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (250, 'Move it, Shake it, Lift it', 'Cardio', '9:33 AM', '11:08 AM', 13, 0.7, 77);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (251, 'Curls n’ Crunches', 'Strength', '9:29 AM', '5:34 PM', 7, 0.78, 9);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (252, 'Abs Fab / Fab Abs', 'Cardio', '11:47 AM', '4:08 PM', 20, 0.1, 57);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (253, 'Power Hour', 'Abs', '1:17 PM', '1:43 PM', 7, 0.02, 12);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (254, 'Fab & Fit & Fun', 'Cardio', '11:38 AM', '5:58 PM', 20, 0.93, 71);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (255, 'Walk this Weigh', 'Cardio', '11:12 AM', '11:21 AM', 11, 0.5, 89);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (256, 'Abs Fab / Fab Abs', 'Abs', '5:44 PM', '6:01 PM', 7, 0.93, 48);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (257, 'Walk this Weigh', 'Cardio', '1:57 PM', '3:58 PM', 9, 0.73, 4);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (258, 'Abs Fab / Fab Abs', 'Abs', '10:14 AM', '11:33 AM', 12, 0.68, 97);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (259, 'Fab & Fit & Fun', 'Strength', '2:48 PM', '3:09 PM', 6, 0.81, 1);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (260, 'Wishful Shrinking', 'Cardio', '11:10 AM', '3:49 PM', 21, 0.42, 99);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (261, 'Fab & Fit & Fun', 'Abs', '12:26 PM', '9:42 AM', 22, 0.58, 38);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (262, 'Walk this Weigh', 'Strength', '11:42 AM', '3:42 PM', 25, 0.65, 15);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (263, 'Move it, Shake it, Lift it', 'Cardio', '2:06 PM', '6:15 PM', 9, 0.64, 85);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (264, 'Move it, Shake it, Lift it', 'Strength', '1:05 PM', '11:32 AM', 6, 0.34, 7);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (265, 'Fab & Fit & Fun', 'Abs', '12:50 PM', '2:16 PM', 6, 0.19, 26);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (266, 'Move it, Shake it, Lift it', 'Yoga', '11:07 AM', '2:38 PM', 16, 0.1, 59);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (267, 'Curls n’ Crunches', 'Cardio', '10:27 AM', '4:55 PM', 29, 0.29, 57);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (268, 'Power Hour', 'Cardio', '4:27 PM', '6:18 PM', 18, 0.07, 32);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (269, 'Wishful Shrinking', 'Cardio', '9:13 AM', '7:08 PM', 16, 0.54, 27);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (270, 'Curls n’ Crunches', 'Cardio', '11:08 AM', '2:46 PM', 26, 0.02, 9);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (271, 'Abs Fab / Fab Abs', 'Abs', '12:47 PM', '10:01 AM', 14, 0.81, 46);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (272, 'Curls n’ Crunches', 'Abs', '11:20 AM', '9:08 AM', 17, 0.73, 2);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (273, 'Walk this Weigh', 'Abs', '8:18 AM', '5:11 PM', 24, 0.93, 50);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (274, 'Curls n’ Crunches', 'Abs', '2:34 PM', '2:58 PM', 27, 0.1, 62);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (275, 'Move it, Shake it, Lift it', 'Cardio', '9:14 AM', '4:05 PM', 8, 0.42, 11);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (276, 'Walk this Weigh', 'Abs', '10:26 AM', '6:37 PM', 28, 1.0, 80);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (277, 'Abs Fab / Fab Abs', 'Cardio', '11:53 AM', '11:06 AM', 10, 0.9, 36);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (278, 'Sweat', 'Abs', '4:07 PM', '9:32 AM', 7, 0.3, 84);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (279, 'Walk this Weigh', 'Strength', '4:34 PM', '11:31 AM', 8, 0.97, 57);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (280, 'Move it, Shake it, Lift it', 'Abs', '11:13 AM', '1:41 PM', 28, 0.92, 19);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (281, 'Wishful Shrinking', 'Abs', '3:42 PM', '2:50 PM', 21, 0.31, 33);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (282, 'Fab & Fit & Fun', 'Abs', '3:14 PM', '5:24 PM', 13, 0.91, 45);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (283, 'Move it, Shake it, Lift it', 'Strength', '8:38 AM', '12:26 PM', 15, 0.8, 37);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (284, 'Abs Fab / Fab Abs', 'Cardio', '10:30 AM', '1:09 PM', 12, 0.97, 90);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (285, 'Power Hour', 'Yoga', '10:43 AM', '2:35 PM', 20, 0.21, 53);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (286, 'Sweat', 'Cardio', '8:56 AM', '12:32 PM', 24, 0.54, 22);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (287, 'Abs Fab / Fab Abs', 'Cardio', '8:18 AM', '2:12 PM', 11, 0.39, 79);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (288, 'Walk this Weigh', 'Strength', '5:04 PM', '3:23 PM', 15, 0.62, 12);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (289, 'Abs Fab / Fab Abs', 'Cardio', '11:19 AM', '9:31 AM', 15, 0.75, 39);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (290, 'Move it, Shake it, Lift it', 'Strength', '1:44 PM', '5:02 PM', 22, 0.92, 51);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (291, 'Move it, Shake it, Lift it', 'Abs', '4:27 PM', '2:57 PM', 9, 0.1, 54);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (292, 'Wishful Shrinking', 'Cardio', '9:09 AM', '10:28 AM', 15, 0.37, 12);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (293, 'Power Hour', 'Abs', '4:42 PM', '2:49 PM', 14, 0.31, 65);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (294, 'Sweat', 'Cardio', '5:30 PM', '1:46 PM', 29, 0.19, 47);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (295, 'Abs Fab / Fab Abs', 'Cardio', '9:28 AM', '12:47 PM', 26, 0.6, 53);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (296, 'Power Hour', 'Strength', '3:26 PM', '6:20 PM', 9, 0.2, 63);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (297, 'Fab & Fit & Fun', 'Yoga', '1:56 PM', '12:41 PM', 20, 0.0, 94);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (298, 'Fab & Fit & Fun', 'Abs', '1:42 PM', '4:46 PM', 30, 0.19, 88);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (299, 'Fab & Fit & Fun', 'Abs', '4:26 PM', '1:49 PM', 27, 0.81, 34);
insert into class_mock (id, class_name, class_type, start_time, end_time, class_size, enroll, instructor) values (300, 'Move it, Shake it, Lift it', 'Cardio', '8:24 AM', '12:32 PM', 13, 0.88, 19);
